-- views can only be fully collapsed with the global statusline
vim.opt.laststatus = 3
-- Default splitting will cause your main splits to jump when opening an edgebar.
-- To prevent this, set `splitkeep` to either `screen` or `topline`.
vim.opt.splitkeep = "screen"

return {
  --{
    --"yetone/avante.nvim",
    --event = "VeryLazy",
    --lazy = false,
    --version = false,
    --opts = {
      --provider = "copilot",
      --auto_suggestions_provider = "copilot",
    --},
    --build = "make",
    --dependencies = {
      --"nvim-treesitter/nvim-treesitter",
      --"stevearc/dressing.nvim",
      --"nvim-lua/plenary.nvim",
      --"MunifTanjim/nui.nvim",
      --"nvim-tree/nvim-web-devicons",
      --"zbirenbaum/copilot.lua",
      --{
        --"HakonHarnes/img-clip.nvim",
        --event = "VeryLazy",
        --opts = {
          ---- recommended settings
          --default = {
            --embed_image_as_base64 = false,
            --prompt_for_file_name = false,
            --drag_and_drop = {
              --insert_mode = true,
            --},
            ---- required for Windows users
            --use_absolute_path = true,
          --},
        --},
      --},
      --{
        --'MeanderingProgrammer/render-markdown.nvim',
        --opts = {
          --file_types = { "markdown", "Avante" },
        --},
        --ft = { "markdown", "Avante" },
      --},
    --},
  --},
  ----{
    ----'github/copilot.vim'
  ----},
  --{
    --"supermaven-inc/supermaven-nvim",
    --config = function()
      --require("supermaven-nvim").setup({})
    --end,
  --}
}
